Readme and favicon
JSConfCL/TechTon-landing pull request #7
Opened 2024-02-04 23:47 UTC by odracirdev

I updated the readme and favicon.ico

2024-02-04 23:51 UTC, Dereemii commented on README.md
> +Somos varias comunidades tech unidas que brindaremos charlas y workshops gratuitos mediante streaming para recaudar fondos que serán entregados a [Bomberos de Chile](https://www.instagram.com/p/C243r
Agregaría somos varias comunidades tech unidads, bajo el alero de JavaScriptChile

2024-02-04 23:51 UTC, Dereemii requested changes
modificar comentario plis

2024-02-04 23:52 UTC, Alais29 commented on README.md
> +Somos varias comunidades tech unidas que brindaremos charlas y workshops gratuitos mediante streaming para recaudar fondos que serán entregados a [Bomberos de Chile](https://www.instagram.com/p/C243r
debería ser "...y así", en lugar de "...u así"

2024-02-04 23:58 UTC, odracirdev commented on README.md
> +Somos varias comunidades tech unidas que brindaremos charlas y workshops gratuitos mediante streaming para recaudar fondos que serán entregados a [Bomberos de Chile](https://www.instagram.com/p/C243r
Perfecto, lo agrego

2024-02-04 23:58 UTC, odracirdev commented on README.md
> +Somos varias comunidades tech unidas que brindaremos charlas y workshops gratuitos mediante streaming para recaudar fondos que serán entregados a [Bomberos de Chile](https://www.instagram.com/p/C243r
Error de typo, ya envío la corrección

2024-02-05 00:03 UTC, odracirdev commented
Actualizado 🤗

2024-02-05 00:07 UTC, Alais29 approved these changes

2024-02-05 00:08 UTC, Dereemii approved these changes

2024-02-05 00:40 UTC, Alais29 approved these changes

2024-02-05 00:42 UTC, closed without merging